ARG version
FROM almalinux:${version:-8}
ARG COURSE="Docker" \
    TRAINER="Sivakumar" \
    TRAINEE="Akhil" \
    DURATION="10HRS" \
    AUTHOR="joindevops"
RUN echo "Trainee is: ${TRAINEE}, version is: ${version}"
CMD ["sleep", "200"]